name: Coordinated Federated Learning
server:
  num-round: 20
  clients: 3
  model: LeNet_CIFAR10
  data-name: CIFAR10
  parameters:
    load: True
    save: True
  validation: True
  data-mode: even
  algorithm: feel
  data-distribution:
    num-data-range:
      - 500
      - 750
    non-iid-rate: 0.5
    refresh-each-round: True
  random-seed: 1
  client-selection:
    enable: True
    mode: random
  optimizer: adam   
  client-cluster:
    cluster_iter: 5 
    enable: True
    cluster: AffinityPropagation
    KMeans:
      mode: auto
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000
  accuracy-drop: 20.0
  stop-when-false: False
  send-mail:
    active: False
    sender-email: 'example1@email.com'
    password: 'admin'
    receiver-email: 'example2@email.com'
  csfedavg:
    p: 0.5
    alpha: 0.3
  fedcls:
    ratio: 0.20
  fedrhlp:
    c1: 0.5
    c2: 0.5
  hicsfl:
    num_cluster: 3
    selection_ratio: 0.2
  feel:
    selected_ratio: 0.5


rabbit:
  address: 192.0.0.0
  username: 1
  password: 1

log_path: .

learning:
  learning-rate: 0.05
  momentum: 0.5
  batch-size: 128
  clip-grad-norm: 0
